baseURL = 'https://stark.software/'
locale = 'en_GB'
title = 'Stark Software'

disableKinds = ['rss', 'taxonomy', 'term']

[markup.highlight]
style = 'github'
noClasses = false

[params]
description = 'Open-source window management, window tags, keyboard shortcuts, and status bars for macOS.'
htmlLang = 'en-GB'

[[menu.main]]
name = 'Home'
url = '/'
weight = 1
[[menu.main]]
name = 'swm'
url = '/swm/'
weight = 3
[[menu.main]]
name = 'stags'
url = '/stags/'
weight = 4
[[menu.main]]
name = 'skbd'
url = '/skbd/'
weight = 5

[[menu.main]]
name = 'sbar'
url = '/sbar/'
weight = 6

[[menu.footer]]
name = 'GitHub'
weight = 1
url = 'https://github.com/starkwm'
